apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  selector:
    matchLabels:
      app: customer-service
      tier: api
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customer-service
        tier: api
    spec:
      containers:
      - name: customer-service
        image: aklearning/eng-lab-customer-service
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: DB_HOST
          value: customer-service-db
        - name: DB_NAME
          value: customer-service
        - name: DB_PASSWORD
          value: guest
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: guest
        ports:
        - containerPort: 5000
